#!/usr/bin/env python3
"""
reviewer/Metrics/ld_decay.py

LD decay analysis using pre-computed r² values from the main analysis workflow.

Input data:
    pop.ld_decay_total.xls   — 1,000,000 rows: distance (kb) vs mean r² (Pop)
    pop.ld_decay_distance.xls — summary: half-decay and 0.1-decay distances

These files were generated by the BGI/华大 population genomics workflow
(PopLDdecay) from the full (non-LD-pruned) VCF dataset.

Outputs (written to reviewer/Metrics/):
    ld_decay.png            — LD decay curve (300 DPI)
    ld_decay_summary.tsv    — half-decay and 0.1-decay distances

Dependencies: pandas, numpy, matplotlib
"""

import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ── Paths ──────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR   = os.path.join(SCRIPT_DIR, "..", "..")

LD_DIR   = os.path.join(
    BASE_DIR, "..", "..",
    "Mango-华大重测序-变异检测+遗传进化",
    "evo", "workflow_results", "data", "06.LD", "results"
)
LD_TOTAL  = os.path.join(LD_DIR, "pop.ld_decay_total.xls")
LD_DIST   = os.path.join(LD_DIR, "pop.ld_decay_distance.xls")

OUT_PNG   = os.path.join(SCRIPT_DIR, "ld_decay.png")
OUT_TSV   = os.path.join(SCRIPT_DIR, "ld_decay_summary.tsv")

# ── Load data ──────────────────────────────────────────────────────────────
print("Loading LD decay data …")
ld = pd.read_csv(LD_TOTAL, sep="\t")          # columns: distance, Pop
ld.columns = ["dist_kb", "r2"]
print(f"  {len(ld):,} data points  |  distance range: "
      f"{ld['dist_kb'].min():.3f}–{ld['dist_kb'].max():.0f} kb")

dist_df = pd.read_csv(LD_DIST, sep="\t")      # popid, half.decay, decay01
print(f"\nDecay summary:\n{dist_df.to_string(index=False)}")
dist_df.to_csv(OUT_TSV, sep="\t", index=False)
print(f"Saved: {OUT_TSV}")

# ── Half-decay and r²=0.1 distances ───────────────────────────────────────
half_decay   = float(dist_df["half.decay"].iloc[0])
decay01      = float(dist_df["decay01"].iloc[0])
r2_at_start  = float(ld["r2"].iloc[0])
r2_half      = r2_at_start / 2.0

# ── Subsample for smooth plotting (every 10th point) ──────────────────────
ld_plot = ld.iloc[::10].copy()

# ── Plot ───────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 6))

ax.plot(ld_plot["dist_kb"], ld_plot["r2"],
        color="#2166ac", linewidth=1.8, label="Mean r² (all samples)")

# Annotate half-decay
ax.axhline(r2_half, color="#888888", linewidth=0.8, linestyle="--", alpha=0.7)
ax.axvline(half_decay, color="#d73027", linewidth=1.0, linestyle="--", alpha=0.8)
ax.annotate(
    f"Half-decay: {half_decay:.1f} kb\n(r² = {r2_half:.3f})",
    xy=(half_decay, r2_half),
    xytext=(half_decay + 30, r2_half + 0.04),
    arrowprops=dict(arrowstyle="->", color="#d73027", lw=0.9),
    fontsize=9, color="#d73027", fontweight="bold"
)

# Annotate r²=0.1 threshold
ax.axhline(0.1, color="#888888", linewidth=0.8, linestyle=":", alpha=0.7)
ax.axvline(decay01, color="#4dac26", linewidth=1.0, linestyle=":", alpha=0.8)
ax.annotate(
    f"r² = 0.1 at {decay01:.1f} kb",
    xy=(decay01, 0.1),
    xytext=(decay01 + 30, 0.1 + 0.04),
    arrowprops=dict(arrowstyle="->", color="#4dac26", lw=0.9),
    fontsize=9, color="#4dac26", fontweight="bold"
)

ax.set_xlabel("Physical distance (kb)", fontsize=12, fontweight="bold")
ax.set_ylabel("r²  (linkage disequilibrium)", fontsize=12, fontweight="bold")
ax.set_title(
    "LD Decay — Mango WGS (n=60, full SNP dataset)",
    fontsize=13, fontweight="bold"
)
ax.set_xlim(0, 500)
ax.set_ylim(0, min(1.0, ld_plot["r2"].max() * 1.05 + 0.02))
ax.yaxis.grid(True, linestyle="--", alpha=0.4)
ax.set_axisbelow(True)
ax.tick_params(labelsize=10)
ax.legend(fontsize=10, framealpha=0.9)

plt.tight_layout()
plt.savefig(OUT_PNG, dpi=300, bbox_inches="tight", facecolor="white")
print(f"Saved: {OUT_PNG}")
